name: Deploy VuePress to GitHub Pages

on:
  push:
    branches:
      - master  # 或者您的默认分支名称，如master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'  # VuePress v1 需要 Node.js 14
          cache: 'npm'

      - name: Debug - List Files
        run: |
          echo "Listing workspace files:"
          ls -la
          echo "Listing docs directory:"
          ls -la docs/
          echo "Checking .vuepress directory:"
          ls -la docs/.vuepress/ || echo "Directory does not exist!"
          echo "Checking package.json:"
          cat package.json
          echo "Checking node_modules:"
          ls -la node_modules/ || echo "node_modules not found!"
          echo "Checking Node.js version:"
          node -v

      - name: Install Dependencies
        run: |
          echo "Installing dependencies..."
          npm install
          echo "Checking installed packages:"
          npm list --depth=0

      - name: Build VuePress Site
        run: |
          echo "Starting build process..."
          npm run docs:build
          echo "Build completed. Listing output:"
          ls -la docs/.vuepress/dist/ || echo "Build directory not found!"
          echo "Checking for any errors in the build process..."

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs/.vuepress/dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4